/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DataUserFansResponseData
 */

public class DataUserFansResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("total_fans")
  private String totalFans = null;

  @SerializedName("new_fans")
  private String newFans = null;

  @SerializedName("date_new_fans")
  private String dateNewFans = null;

  public DataUserFansResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public DataUserFansResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DataUserFansResponseData totalFans(String totalFans) {
    this.totalFans = totalFans;
    return this;
  }

   /**
   * 总粉丝数
   * @return totalFans
  **/
  public String getTotalFans() {
    return totalFans;
  }

  public void setTotalFans(String totalFans) {
    this.totalFans = totalFans;
  }

  public DataUserFansResponseData newFans(String newFans) {
    this.newFans = newFans;
    return this;
  }

   /**
   * 新粉丝
   * @return newFans
  **/
  public String getNewFans() {
    return newFans;
  }

  public void setNewFans(String newFans) {
    this.newFans = newFans;
  }

  public DataUserFansResponseData dateNewFans(String dateNewFans) {
    this.dateNewFans = dateNewFans;
    return this;
  }

   /**
   * 每天新粉丝数
   * @return dateNewFans
  **/
  public String getDateNewFans() {
    return dateNewFans;
  }

  public void setDateNewFans(String dateNewFans) {
    this.dateNewFans = dateNewFans;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataUserFansResponseData dataUserFansResponseData = (DataUserFansResponseData) o;
    return Objects.equals(this.errorCode, dataUserFansResponseData.errorCode) &&
        Objects.equals(this.description, dataUserFansResponseData.description) &&
        Objects.equals(this.totalFans, dataUserFansResponseData.totalFans) &&
        Objects.equals(this.newFans, dataUserFansResponseData.newFans) &&
        Objects.equals(this.dateNewFans, dataUserFansResponseData.dateNewFans);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, totalFans, newFans, dateNewFans);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataUserFansResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    totalFans: ").append(toIndentedString(totalFans)).append("\n");
    sb.append("    newFans: ").append(toIndentedString(newFans)).append("\n");
    sb.append("    dateNewFans: ").append(toIndentedString(dateNewFans)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
