/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DataPoiDetailPageResponseData
 */

public class DataPoiDetailPageResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("uv")
  private String uv = null;

  @SerializedName("pv")
  private String pv = null;

  @SerializedName("item_play")
  private String itemPlay = null;

  @SerializedName("average_item_play")
  private String averageItemPlay = null;

  @SerializedName("head_click_pv")
  private String headClickPv = null;

  @SerializedName("phone_click_uv")
  private String phoneClickUv = null;

  @SerializedName("phone_click_pv")
  private String phoneClickPv = null;

  @SerializedName("collect_pv")
  private String collectPv = null;

  @SerializedName("card_show_pv")
  private String cardShowPv = null;

  @SerializedName("card_click_pv")
  private String cardClickPv = null;

  public DataPoiDetailPageResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public DataPoiDetailPageResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DataPoiDetailPageResponseData uv(String uv) {
    this.uv = uv;
    return this;
  }

   /**
   * 每天门店UV
   * @return uv
  **/
  public String getUv() {
    return uv;
  }

  public void setUv(String uv) {
    this.uv = uv;
  }

  public DataPoiDetailPageResponseData pv(String pv) {
    this.pv = pv;
    return this;
  }

   /**
   * 每天门店PV
   * @return pv
  **/
  public String getPv() {
    return pv;
  }

  public void setPv(String pv) {
    this.pv = pv;
  }

  public DataPoiDetailPageResponseData itemPlay(String itemPlay) {
    this.itemPlay = itemPlay;
    return this;
  }

   /**
   * 每天门店视频播放vv
   * @return itemPlay
  **/
  public String getItemPlay() {
    return itemPlay;
  }

  public void setItemPlay(String itemPlay) {
    this.itemPlay = itemPlay;
  }

  public DataPoiDetailPageResponseData averageItemPlay(String averageItemPlay) {
    this.averageItemPlay = averageItemPlay;
    return this;
  }

   /**
   * 每天人均视频查看数
   * @return averageItemPlay
  **/
  public String getAverageItemPlay() {
    return averageItemPlay;
  }

  public void setAverageItemPlay(String averageItemPlay) {
    this.averageItemPlay = averageItemPlay;
  }

  public DataPoiDetailPageResponseData headClickPv(String headClickPv) {
    this.headClickPv = headClickPv;
    return this;
  }

   /**
   * 每天企业头像点击PV
   * @return headClickPv
  **/
  public String getHeadClickPv() {
    return headClickPv;
  }

  public void setHeadClickPv(String headClickPv) {
    this.headClickPv = headClickPv;
  }

  public DataPoiDetailPageResponseData phoneClickUv(String phoneClickUv) {
    this.phoneClickUv = phoneClickUv;
    return this;
  }

   /**
   * 每天电话点击UV
   * @return phoneClickUv
  **/
  public String getPhoneClickUv() {
    return phoneClickUv;
  }

  public void setPhoneClickUv(String phoneClickUv) {
    this.phoneClickUv = phoneClickUv;
  }

  public DataPoiDetailPageResponseData phoneClickPv(String phoneClickPv) {
    this.phoneClickPv = phoneClickPv;
    return this;
  }

   /**
   * 每天电话点击PV
   * @return phoneClickPv
  **/
  public String getPhoneClickPv() {
    return phoneClickPv;
  }

  public void setPhoneClickPv(String phoneClickPv) {
    this.phoneClickPv = phoneClickPv;
  }

  public DataPoiDetailPageResponseData collectPv(String collectPv) {
    this.collectPv = collectPv;
    return this;
  }

   /**
   * 每天门店收藏PV
   * @return collectPv
  **/
  public String getCollectPv() {
    return collectPv;
  }

  public void setCollectPv(String collectPv) {
    this.collectPv = collectPv;
  }

  public DataPoiDetailPageResponseData cardShowPv(String cardShowPv) {
    this.cardShowPv = cardShowPv;
    return this;
  }

   /**
   * 每天商业化卡片展示PV
   * @return cardShowPv
  **/
  public String getCardShowPv() {
    return cardShowPv;
  }

  public void setCardShowPv(String cardShowPv) {
    this.cardShowPv = cardShowPv;
  }

  public DataPoiDetailPageResponseData cardClickPv(String cardClickPv) {
    this.cardClickPv = cardClickPv;
    return this;
  }

   /**
   * 每天商业化卡片点击PV
   * @return cardClickPv
  **/
  public String getCardClickPv() {
    return cardClickPv;
  }

  public void setCardClickPv(String cardClickPv) {
    this.cardClickPv = cardClickPv;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataPoiDetailPageResponseData dataPoiDetailPageResponseData = (DataPoiDetailPageResponseData) o;
    return Objects.equals(this.errorCode, dataPoiDetailPageResponseData.errorCode) &&
        Objects.equals(this.description, dataPoiDetailPageResponseData.description) &&
        Objects.equals(this.uv, dataPoiDetailPageResponseData.uv) &&
        Objects.equals(this.pv, dataPoiDetailPageResponseData.pv) &&
        Objects.equals(this.itemPlay, dataPoiDetailPageResponseData.itemPlay) &&
        Objects.equals(this.averageItemPlay, dataPoiDetailPageResponseData.averageItemPlay) &&
        Objects.equals(this.headClickPv, dataPoiDetailPageResponseData.headClickPv) &&
        Objects.equals(this.phoneClickUv, dataPoiDetailPageResponseData.phoneClickUv) &&
        Objects.equals(this.phoneClickPv, dataPoiDetailPageResponseData.phoneClickPv) &&
        Objects.equals(this.collectPv, dataPoiDetailPageResponseData.collectPv) &&
        Objects.equals(this.cardShowPv, dataPoiDetailPageResponseData.cardShowPv) &&
        Objects.equals(this.cardClickPv, dataPoiDetailPageResponseData.cardClickPv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, uv, pv, itemPlay, averageItemPlay, headClickPv, phoneClickUv, phoneClickPv, collectPv, cardShowPv, cardClickPv);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataPoiDetailPageResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    uv: ").append(toIndentedString(uv)).append("\n");
    sb.append("    pv: ").append(toIndentedString(pv)).append("\n");
    sb.append("    itemPlay: ").append(toIndentedString(itemPlay)).append("\n");
    sb.append("    averageItemPlay: ").append(toIndentedString(averageItemPlay)).append("\n");
    sb.append("    headClickPv: ").append(toIndentedString(headClickPv)).append("\n");
    sb.append("    phoneClickUv: ").append(toIndentedString(phoneClickUv)).append("\n");
    sb.append("    phoneClickPv: ").append(toIndentedString(phoneClickPv)).append("\n");
    sb.append("    collectPv: ").append(toIndentedString(collectPv)).append("\n");
    sb.append("    cardShowPv: ").append(toIndentedString(cardShowPv)).append("\n");
    sb.append("    cardClickPv: ").append(toIndentedString(cardClickPv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
