/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DataUserPageResponseData
 */

public class DataUserPageResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("total_view")
  private String totalView = null;

  @SerializedName("new_view")
  private String newView = null;

  @SerializedName("date_new_view")
  private String dateNewView = null;

  public DataUserPageResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public DataUserPageResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DataUserPageResponseData totalView(String totalView) {
    this.totalView = totalView;
    return this;
  }

   /**
   * 主页访问UV
   * @return totalView
  **/
  public String getTotalView() {
    return totalView;
  }

  public void setTotalView(String totalView) {
    this.totalView = totalView;
  }

  public DataUserPageResponseData newView(String newView) {
    this.newView = newView;
    return this;
  }

   /**
   * 新增主页访问数
   * @return newView
  **/
  public String getNewView() {
    return newView;
  }

  public void setNewView(String newView) {
    this.newView = newView;
  }

  public DataUserPageResponseData dateNewView(String dateNewView) {
    this.dateNewView = dateNewView;
    return this;
  }

   /**
   * 每天新增主页访问数
   * @return dateNewView
  **/
  public String getDateNewView() {
    return dateNewView;
  }

  public void setDateNewView(String dateNewView) {
    this.dateNewView = dateNewView;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataUserPageResponseData dataUserPageResponseData = (DataUserPageResponseData) o;
    return Objects.equals(this.errorCode, dataUserPageResponseData.errorCode) &&
        Objects.equals(this.description, dataUserPageResponseData.description) &&
        Objects.equals(this.totalView, dataUserPageResponseData.totalView) &&
        Objects.equals(this.newView, dataUserPageResponseData.newView) &&
        Objects.equals(this.dateNewView, dataUserPageResponseData.dateNewView);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, totalView, newView, dateNewView);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataUserPageResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    totalView: ").append(toIndentedString(totalView)).append("\n");
    sb.append("    newView: ").append(toIndentedString(newView)).append("\n");
    sb.append("    dateNewView: ").append(toIndentedString(dateNewView)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
