/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DataPoiShopPageResponseData
 */

public class DataPoiShopPageResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("uv")
  private String uv = null;

  @SerializedName("pv")
  private String pv = null;

  @SerializedName("link_count")
  private String linkCount = null;

  @SerializedName("phone_count")
  private String phoneCount = null;

  @SerializedName("challenge_count")
  private String challengeCount = null;

  public DataPoiShopPageResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public DataPoiShopPageResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DataPoiShopPageResponseData uv(String uv) {
    this.uv = uv;
    return this;
  }

   /**
   * 每天主页UV
   * @return uv
  **/
  public String getUv() {
    return uv;
  }

  public void setUv(String uv) {
    this.uv = uv;
  }

  public DataPoiShopPageResponseData pv(String pv) {
    this.pv = pv;
    return this;
  }

   /**
   * 每天主页PV
   * @return pv
  **/
  public String getPv() {
    return pv;
  }

  public void setPv(String pv) {
    this.pv = pv;
  }

  public DataPoiShopPageResponseData linkCount(String linkCount) {
    this.linkCount = linkCount;
    return this;
  }

   /**
   * 每天官网链接点击
   * @return linkCount
  **/
  public String getLinkCount() {
    return linkCount;
  }

  public void setLinkCount(String linkCount) {
    this.linkCount = linkCount;
  }

  public DataPoiShopPageResponseData phoneCount(String phoneCount) {
    this.phoneCount = phoneCount;
    return this;
  }

   /**
   * 每天联系电话点击量
   * @return phoneCount
  **/
  public String getPhoneCount() {
    return phoneCount;
  }

  public void setPhoneCount(String phoneCount) {
    this.phoneCount = phoneCount;
  }

  public DataPoiShopPageResponseData challengeCount(String challengeCount) {
    this.challengeCount = challengeCount;
    return this;
  }

   /**
   * 每天挑战点击量
   * @return challengeCount
  **/
  public String getChallengeCount() {
    return challengeCount;
  }

  public void setChallengeCount(String challengeCount) {
    this.challengeCount = challengeCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataPoiShopPageResponseData dataPoiShopPageResponseData = (DataPoiShopPageResponseData) o;
    return Objects.equals(this.errorCode, dataPoiShopPageResponseData.errorCode) &&
        Objects.equals(this.description, dataPoiShopPageResponseData.description) &&
        Objects.equals(this.uv, dataPoiShopPageResponseData.uv) &&
        Objects.equals(this.pv, dataPoiShopPageResponseData.pv) &&
        Objects.equals(this.linkCount, dataPoiShopPageResponseData.linkCount) &&
        Objects.equals(this.phoneCount, dataPoiShopPageResponseData.phoneCount) &&
        Objects.equals(this.challengeCount, dataPoiShopPageResponseData.challengeCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, uv, pv, linkCount, phoneCount, challengeCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataPoiShopPageResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    uv: ").append(toIndentedString(uv)).append("\n");
    sb.append("    pv: ").append(toIndentedString(pv)).append("\n");
    sb.append("    linkCount: ").append(toIndentedString(linkCount)).append("\n");
    sb.append("    phoneCount: ").append(toIndentedString(phoneCount)).append("\n");
    sb.append("    challengeCount: ").append(toIndentedString(challengeCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
