/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DataCustomerLetterResponseData
 */

public class DataCustomerLetterResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("enter_auto_reply")
  private String enterAutoReply = null;

  @SerializedName("keyword_auto_replay")
  private String keywordAutoReplay = null;

  @SerializedName("letter_click_count")
  private String letterClickCount = null;

  public DataCustomerLetterResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public DataCustomerLetterResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DataCustomerLetterResponseData enterAutoReply(String enterAutoReply) {
    this.enterAutoReply = enterAutoReply;
    return this;
  }

   /**
   * 每天进入对话自动回复数
   * @return enterAutoReply
  **/
  public String getEnterAutoReply() {
    return enterAutoReply;
  }

  public void setEnterAutoReply(String enterAutoReply) {
    this.enterAutoReply = enterAutoReply;
  }

  public DataCustomerLetterResponseData keywordAutoReplay(String keywordAutoReplay) {
    this.keywordAutoReplay = keywordAutoReplay;
    return this;
  }

   /**
   * 每天关键词自动回复数
   * @return keywordAutoReplay
  **/
  public String getKeywordAutoReplay() {
    return keywordAutoReplay;
  }

  public void setKeywordAutoReplay(String keywordAutoReplay) {
    this.keywordAutoReplay = keywordAutoReplay;
  }

  public DataCustomerLetterResponseData letterClickCount(String letterClickCount) {
    this.letterClickCount = letterClickCount;
    return this;
  }

   /**
   * 每天私信菜单点击量
   * @return letterClickCount
  **/
  public String getLetterClickCount() {
    return letterClickCount;
  }

  public void setLetterClickCount(String letterClickCount) {
    this.letterClickCount = letterClickCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataCustomerLetterResponseData dataCustomerLetterResponseData = (DataCustomerLetterResponseData) o;
    return Objects.equals(this.errorCode, dataCustomerLetterResponseData.errorCode) &&
        Objects.equals(this.description, dataCustomerLetterResponseData.description) &&
        Objects.equals(this.enterAutoReply, dataCustomerLetterResponseData.enterAutoReply) &&
        Objects.equals(this.keywordAutoReplay, dataCustomerLetterResponseData.keywordAutoReplay) &&
        Objects.equals(this.letterClickCount, dataCustomerLetterResponseData.letterClickCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, enterAutoReply, keywordAutoReplay, letterClickCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataCustomerLetterResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enterAutoReply: ").append(toIndentedString(enterAutoReply)).append("\n");
    sb.append("    keywordAutoReplay: ").append(toIndentedString(keywordAutoReplay)).append("\n");
    sb.append("    letterClickCount: ").append(toIndentedString(letterClickCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
