/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DataUserLikeResponseData
 */

public class DataUserLikeResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("total_like")
  private String totalLike = null;

  @SerializedName("date_new_like")
  private String dateNewLike = null;

  public DataUserLikeResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public DataUserLikeResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DataUserLikeResponseData totalLike(String totalLike) {
    this.totalLike = totalLike;
    return this;
  }

   /**
   * 总点赞
   * @return totalLike
  **/
  public String getTotalLike() {
    return totalLike;
  }

  public void setTotalLike(String totalLike) {
    this.totalLike = totalLike;
  }

  public DataUserLikeResponseData dateNewLike(String dateNewLike) {
    this.dateNewLike = dateNewLike;
    return this;
  }

   /**
   * 每天新增点赞
   * @return dateNewLike
  **/
  public String getDateNewLike() {
    return dateNewLike;
  }

  public void setDateNewLike(String dateNewLike) {
    this.dateNewLike = dateNewLike;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataUserLikeResponseData dataUserLikeResponseData = (DataUserLikeResponseData) o;
    return Objects.equals(this.errorCode, dataUserLikeResponseData.errorCode) &&
        Objects.equals(this.description, dataUserLikeResponseData.description) &&
        Objects.equals(this.totalLike, dataUserLikeResponseData.totalLike) &&
        Objects.equals(this.dateNewLike, dataUserLikeResponseData.dateNewLike);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, totalLike, dateNewLike);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataUserLikeResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    totalLike: ").append(toIndentedString(totalLike)).append("\n");
    sb.append("    dateNewLike: ").append(toIndentedString(dateNewLike)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
