/*
 * 企业号信息查询
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EnterpriseVerifyInfoResponseData
 */

public class EnterpriseVerifyInfoResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("open_id")
  private String openId = null;

  @SerializedName("authentication")
  private String authentication = null;

  @SerializedName("industry_code")
  private Integer industryCode = null;

  @SerializedName("business_license")
  private String businessLicense = null;

  @SerializedName("license")
  private String license = null;

  @SerializedName("start_time")
  private String startTime = null;

  @SerializedName("end_time")
  private String endTime = null;

  public EnterpriseVerifyInfoResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public EnterpriseVerifyInfoResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EnterpriseVerifyInfoResponseData openId(String openId) {
    this.openId = openId;
    return this;
  }

   /**
   * 用户在当前应用的唯一标识
   * @return openId
  **/
  public String getOpenId() {
    return openId;
  }

  public void setOpenId(String openId) {
    this.openId = openId;
  }

  public EnterpriseVerifyInfoResponseData authentication(String authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * 认证信息
   * @return authentication
  **/
  public String getAuthentication() {
    return authentication;
  }

  public void setAuthentication(String authentication) {
    this.authentication = authentication;
  }

  public EnterpriseVerifyInfoResponseData industryCode(Integer industryCode) {
    this.industryCode = industryCode;
    return this;
  }

   /**
   * 二级行业信息
   * @return industryCode
  **/
  public Integer getIndustryCode() {
    return industryCode;
  }

  public void setIndustryCode(Integer industryCode) {
    this.industryCode = industryCode;
  }

  public EnterpriseVerifyInfoResponseData businessLicense(String businessLicense) {
    this.businessLicense = businessLicense;
    return this;
  }

   /**
   * 营业执照
   * @return businessLicense
  **/
  public String getBusinessLicense() {
    return businessLicense;
  }

  public void setBusinessLicense(String businessLicense) {
    this.businessLicense = businessLicense;
  }

  public EnterpriseVerifyInfoResponseData license(String license) {
    this.license = license;
    return this;
  }

   /**
   * 营业执照
   * @return license
  **/
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }

  public EnterpriseVerifyInfoResponseData startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * 权益开始时间
   * @return startTime
  **/
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public EnterpriseVerifyInfoResponseData endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * 权益结束时间
   * @return endTime
  **/
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseVerifyInfoResponseData enterpriseVerifyInfoResponseData = (EnterpriseVerifyInfoResponseData) o;
    return Objects.equals(this.errorCode, enterpriseVerifyInfoResponseData.errorCode) &&
        Objects.equals(this.description, enterpriseVerifyInfoResponseData.description) &&
        Objects.equals(this.openId, enterpriseVerifyInfoResponseData.openId) &&
        Objects.equals(this.authentication, enterpriseVerifyInfoResponseData.authentication) &&
        Objects.equals(this.industryCode, enterpriseVerifyInfoResponseData.industryCode) &&
        Objects.equals(this.businessLicense, enterpriseVerifyInfoResponseData.businessLicense) &&
        Objects.equals(this.license, enterpriseVerifyInfoResponseData.license) &&
        Objects.equals(this.startTime, enterpriseVerifyInfoResponseData.startTime) &&
        Objects.equals(this.endTime, enterpriseVerifyInfoResponseData.endTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, openId, authentication, industryCode, businessLicense, license, startTime, endTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseVerifyInfoResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    openId: ").append(toIndentedString(openId)).append("\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    industryCode: ").append(toIndentedString(industryCode)).append("\n");
    sb.append("    businessLicense: ").append(toIndentedString(businessLicense)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
