/*
 * 
 * 仅对内提供
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.douyin.open.model.ImgUrl;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MusicCollectionListResponseDataList
 */

public class MusicCollectionListResponseDataList {
  @SerializedName("title")
  private String title = null;

  @SerializedName("cover")
  private ImgUrl cover = null;

  @SerializedName("author")
  private String author = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("id")
  private Integer id = null;

  public MusicCollectionListResponseDataList title(String title) {
    this.title = title;
    return this;
  }

   /**
   * 音乐标题
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public MusicCollectionListResponseDataList cover(ImgUrl cover) {
    this.cover = cover;
    return this;
  }

   /**
   * Get cover
   * @return cover
  **/
  public ImgUrl getCover() {
    return cover;
  }

  public void setCover(ImgUrl cover) {
    this.cover = cover;
  }

  public MusicCollectionListResponseDataList author(String author) {
    this.author = author;
    return this;
  }

   /**
   * 作者
   * @return author
  **/
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public MusicCollectionListResponseDataList duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * 时长
   * @return duration
  **/
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public MusicCollectionListResponseDataList id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MusicCollectionListResponseDataList musicCollectionListResponseDataList = (MusicCollectionListResponseDataList) o;
    return Objects.equals(this.title, musicCollectionListResponseDataList.title) &&
        Objects.equals(this.cover, musicCollectionListResponseDataList.cover) &&
        Objects.equals(this.author, musicCollectionListResponseDataList.author) &&
        Objects.equals(this.duration, musicCollectionListResponseDataList.duration) &&
        Objects.equals(this.id, musicCollectionListResponseDataList.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, cover, author, duration, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MusicCollectionListResponseDataList {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    cover: ").append(toIndentedString(cover)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
