/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.douyin.open.model;

import java.util.Objects;
import java.util.Arrays;
import com.douyin.open.model.TestDataResponseDataResponse;
import com.douyin.open.model.Video;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * TestDataResponseData
 */

public class TestDataResponseData {
  @SerializedName("error_code")
  private Integer errorCode = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("video_data")
  private List<TestDataResponseDataResponse> videoData = new ArrayList<TestDataResponseDataResponse>();

  @SerializedName("list")
  private List<Video> list = null;

  public TestDataResponseData errorCode(Integer errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public Integer getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }

  public TestDataResponseData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TestDataResponseData videoData(List<TestDataResponseDataResponse> videoData) {
    this.videoData = videoData;
    return this;
  }

  public TestDataResponseData addVideoDataItem(TestDataResponseDataResponse videoDataItem) {
    this.videoData.add(videoDataItem);
    return this;
  }

   /**
   * 见list
   * @return videoData
  **/
  public List<TestDataResponseDataResponse> getVideoData() {
    return videoData;
  }

  public void setVideoData(List<TestDataResponseDataResponse> videoData) {
    this.videoData = videoData;
  }

  public TestDataResponseData list(List<Video> list) {
    this.list = list;
    return this;
  }

  public TestDataResponseData addListItem(Video listItem) {
    if (this.list == null) {
      this.list = new ArrayList<Video>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  public List<Video> getList() {
    return list;
  }

  public void setList(List<Video> list) {
    this.list = list;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestDataResponseData testDataResponseData = (TestDataResponseData) o;
    return Objects.equals(this.errorCode, testDataResponseData.errorCode) &&
        Objects.equals(this.description, testDataResponseData.description) &&
        Objects.equals(this.videoData, testDataResponseData.videoData) &&
        Objects.equals(this.list, testDataResponseData.list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, description, videoData, list);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestDataResponseData {\n");
    
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    videoData: ").append(toIndentedString(videoData)).append("\n");
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
